- hosts: localhost

  vars:
    - my_name: "3DS QR Codes"
    - my_file: "install_3ds_qr_codes"

  tasks:

  - name: "{{ my_name }} - Load RetroNAS config"
    include_vars: retronas_vars.yml

  - name: "{{ my_name }} - configure 3DS directory"
    file:
      path: "{{ retronas_path }}/3ds"
      owner: "{{ retronas_user }}"
      group: "{{ retronas_user }}"
      state: directory

  - name: "{{ my_name }} - configure CIA directory"
    file:
      path: "{{ retronas_path }}/3ds/cia"
      owner: "{{ retronas_user }}"
      group: "{{ retronas_user }}"
      state: directory

  - name: "{{ my_name }} - configure QR codes directory"
    file:
      path: "{{ retronas_path }}/3ds/qr"
      owner: "{{ retronas_user }}"
      group: "{{ retronas_user }}"
      state: directory 

  - name: "{{ my_name }} - install qrencode"
    apt:
       name: qrencode
       state: latest

  - name: "{{ my_name }} - configure cron scheduled task"
    template:
      src: "templates/{{ my_file }}/{{ my_file }}.cron.j2"
      dest: "/etc/cron.d/{{ my_file }}"
      owner: root
      group: root
      mode: '0644'

  - name: "{{ my_name }} - configure QR generator script"
    template:
      src: "templates/{{ my_file }}/{{ my_file }}.sh.j2"
      dest: "{{ retronas_root }}/scripts/{{ my_file }}.sh"
      owner: root
      group: root
      mode: '0755'
