- hosts: localhost

  vars:
    - my_name: "MiSTer CIFS"
    - my_file: "install_mister_cifs"

    - top_level_paths:
      - { name: "games", enabled: "yes" }
      - { name: "saves", enabled: "no" }
      - { name: "savestates", enabled: "no" }
      - { name: "BIOS", enabled: "no" }
      - { name: "wallpapers", enabled: "no" }

  tasks:

  - name: "{{ my_name }} - Include systems map"
    include_vars: "retronas_systems.yml"

  - name: "{{ my_name }} - Load RetroNAS config"
    include_vars: retronas_vars.yml

  - name: "{{ my_name }} - build top level"
    file:
      path: "{{ retronas_path }}/mister"
      owner: "{{ retronas_user }}"
      group: "{{ retronas_user }}"
      state: directory
      mode: "0775"
    notify: "{{ my_name }} - Restart service"

  - name: ""
    stat:
      path: "{{ retronas_path }}/mister/{{ item.mister }}"
    with_items:
      - "{{ system_map }}"
    register: mister_stat

  - name: "{{ my_name }} - removing old symlink layout see issue #21"
    file:
      path: "{{ retronas_path }}/mister/{{ item.item.mister }}"
      state: absent
    with_items:
      - "{{ mister_stat.results }}"
    when: item.stat.islnk is defined and item.stat.islnk == True
    notify: "{{ my_name }} - Restart service"

  - name: "{{ my_name }} - build top level share paths"
    file:
      path: "{{ retronas_path }}/mister/{{ item.name }}"
      owner: "{{ retronas_user }}"
      group: "{{ retronas_user }}"
      state: directory
      mode: "0775"
    with_items:
      "{{ top_level_paths }}"
    when: 
      - item.enabled == "yes"
    notify: "{{ my_name }} - Restart service"

  - name: "{{ my_name }} - build directory layout"
    file:
      src: "../../roms/{{ item.0.src }}"
      dest: "{{ retronas_path }}/mister/{{ item.1.name }}/{{ item.0.mister }}"
      owner: "{{ retronas_user }}"
      group: "{{ retronas_user }}"
      state: link
    with_nested:
      - "{{ system_map }}"
      - "{{ top_level_paths }}"
    when: 
      - item.1.enabled == "yes"
      - item.0.mister | length > 0
    notify: "{{ my_name }} - Restart service"

  - name: "{{ my_name }} - configure includes file"
    ini_file:
      path: /etc/samba/smb.conf
      section: mister
      option: "include"
      value: "/etc/samba/retronas_mister.conf"
    notify: "{{ my_name }} - Restart service"

  - name: "{{ my_name }} - configure retro shares"
    template:
      src: "templates/{{ my_file }}/retronas_mister.conf.j2"
      dest: /etc/samba/retronas_mister.conf
      owner: root
      group: root
      mode: '0644'
    notify: "{{ my_name }} - Restart service"

  handlers:

  - name: "{{ my_name }} - Restart service"
    service:
      name: "{{ item }}"
      state: restarted
    with_items:
      - smbd
      - nmbd
