- hosts: localhost

  vars:
    - my_name: "Netatalk2.X"
    - my_file: "install_netatalk2x"

  tasks:

  - name: "{{ my_name }}  - Load RetroNAS config"
    include_vars: retronas_vars.yml

  - name: "{{ my_name }}  - unhold netatalk package"
    shell: "/usr/bin/apt-mark unhold netatalk"

  - name: "{{ my_name }}  - remove package-based Netatalk"
    apt:
       name: "{{ item }}"
       state: absent
    with_items:
       - netatalk

  - name: "{{ my_name }}  - install dependencies"
    apt:
       name: "{{ item }}"
       state: latest
    with_items:
       - avahi-daemon
       - build-essential
       - make
       - automake
       - autoconf
       - libdb-dev
       - libdb++-dev
       - libavahi-common-dev
       - libavahi-client-dev
       - libavahi-core-dev
       - libdbus-1-dev
       - libssl-dev
       - autotools-dev
       - libtool
       - libcups2-dev
       - libavahi-client-dev
       - libgcrypt20-dev

  - name: "{{ my_name }} - create install script"
    template:
      src: "templates/{{ my_file }}/{{ my_file }}.sh.j2"
      dest: "{{ retronas_root }}/scripts/{{ my_file }}.sh"
      owner: root
      group: root
      mode: '0755'

  - name: "{{ my_name }} - install from source"
    shell: "{{ retronas_root }}/scripts/{{ my_file }}.sh 2>&1 | tee {{ retronas_root }}/log/{{ my_file }}.log"


#  - name: "{{ my_name }} - configure /etc/default/netatalk"
#    template:
#      src: "templates/{{ my_file }}/default.j2"
#      dest: /etc/default/netatalk
#      owner: root
#      group: root
#      mode: '0644'
#    notify: "{{ my_name }} - Restart service"

#  - name: "{{ my_name }} - configure AppleVolumes.default"
#    template:
#      src: "templates/{{ my_file }}/AppleVolumes.default.j2"
#      dest: /etc/netatalk/AppleVolumes.default
#      owner: root
#      group: root
#      mode: '0644'
#    notify: "{{ my_name }} - Restart service"

#  - name: "{{ my_name }} - configure afpd.conf"
#    template:
#      src: "templates/{{ my_file }}/afpd.conf.j2"
#      dest: /etc/netatalk/afpd.conf
#      owner: root
#      group: root
#      mode: '0644'
#    notify: "{{ my_name }} - Restart service"

  - name: "{{ my_name }} - enable startup services"
    service:
      name: "{{ item }}"
      state: started
      enabled: yes
    with_items:
      - avahi-daemon
      - atalkd
      - afpd
      - papd
      - timelord
      - a2boot

  handlers:

  - name: "{{ my_name }} - Restart service"
    service:
      name: "{{ item }}"
      state: restarted
    with_items:
      - avahi-daemon
      - atalkd
      - afpd
      - papd
      - timelord
      - a2boot
