- hosts: localhost

  vars:
    - my_name: "Generic ROM dir"
    - my_file: "install_romdir"
  tasks:

  - name: "{{ my_name }} - Load RetroNAS config"
    include_vars: retronas_vars.yml

  - name: "{{ my_name }} - Build ROM dir layout"
    file:
      path: "{{ retronas_path }}/roms/{{ item }}"
      owner: "{{ retronas_user }}"
      group: "{{ retronas_user }}"
      state: directory
      mode: "0775"
    with_items:
      - "amiga"
      - "amstrad"
      - "apple_ii"
      - "atari_2600"
      - "atari_5200"
      - "atari_7800"
      - "atari_800"
      - "atari_jaguar"
      - "atari_lynx"
      - "atari_st"
      - "bbc_micro"
      - "colecovision"
      - "commodore_16"
      - "commodore_64"
      - "commodore_vic20"
      - "intellivision"
      - "mame"
      - "msx"
      - "nec_pc88"
      - "nec_pc98"
      - "neogeo"
      - "nintendo_famicom"
      - "nintendo_gameboy"
      - "nintendo_gameboyadvance"
      - "nintendo_gamecube"
      - "nintendo_superfamicom"
      - "nintendo_wii"
      - "pcengine"
      - "pcenginecd"
      - "saturn"
      - "sega_mastersystem"
      - "sega_megacd"
      - "sega_megadrive"
      - "sony_ps1"
      - "sony_ps2"
      - "sony_psp"
      - "vextrex"
      - "wonderswan"
      - "x68000"
      - "zx_spectrum"

  - name: "{{ my_name }} - Build ROM dir symlinks"
    file:
      src: "{{ item.src }}"
      dest: "{{ retronas_path }}/roms/{{ item.dest }}"
      owner: "{{ retronas_user }}"
      group: "{{ retronas_user }}"
      state: link
    loop:
      - { src: "nintendo_famicom", dest: "nintendo_nes" }
      - { src: "nintendo_superfamicom", dest: "nintendo_snes" }
      - { src: "sega_megadrive", dest: "sega_genesis" }
      - { src: "sega_megacd", dest: "sega_segacd" }
      - { src: "pcengine", dest: "turbografx16" }
      - { src: "pcenginecd", dest: "turbografxcd" }
