- hosts: localhost

  vars:
    - my_name: "XBox360"
    - my_file: "install_xbox360"
  tasks:

  - name: "{{ my_name }} - Load RetroNAS config"
    include_vars: retronas_vars.yml

  - name: "{{ my_name }} - Build XBox360 layout"
    file:
      path: "{{ retronas_path }}/xbox360/games"
      owner: "{{ retronas_user }}"
      group: "{{ retronas_user }}"
      state: directory
      mode: "0775"
    notify: "{{ my_name }} - Restart service"

  - name: "{{ my_name }} - configure includes file"
    ini_file:
      path: /etc/samba/smb.conf
      section: xbox360
      option: "include"
      value: "/etc/samba/retronas_xbox360.conf"
    notify: "{{ my_name }} - Restart service"

  - name: "{{ my_name }} - configure retro shares"
    template:
      src: "templates/{{ my_file }}/retronas_xbox360.conf.j2"
      dest: /etc/samba/retronas_xbox360.conf
      owner: root
      group: root
      mode: '0644'
    notify: "{{ my_name }} - Restart service"

  handlers:

  - name: "{{ my_name }} - Restart service"
    service:
      name: "{{ item }}"
      state: restarted
    with_items:
      - smbd
      - nmbd
