- hosts: localhost

  vars:
    - my_name: "adtpro"
    - my_file: "install_{{ my_name }}"

    - systemd_units:
      - { name: "adtpro", type: 'service', state: "stopped", enabled: "no", restart: "no", instance: "no" }

    - packages:
      - default-jre
      - xvfb

  tasks:

  - name: "{{ my_name }} - Include systems map"
    include_vars: "retronas_systems.yml"

  - name: "{{ my_name }} - Load RetroNAS config"
    include_vars: retronas_vars.yml

  - name: "{{ my_name }} - Install build tools"
    package:
       name: "{{ packages }}"
       state: latest

  - name: "{{ my_name }} - Generate {{ my_file }} script"
    template:
      src: "templates/{{ my_file }}/{{ my_file }}.sh.j2"
      dest: "{{ retronas_root }}/scripts/{{ my_file }}.sh"
      owner: root
      group: root
      mode: 0755

  - name: "{{ my_name }} - Install"
    shell: "{{ retronas_root }}/scripts/{{ my_file }}.sh 2>&1 | tee {{ retronas_root }}/log/{{ my_file }}.log"
    args:
      creates: "{{ retronas_root}} /opt/zterm/zterm"

  - name: "{{ my_name }} - create startup service(s) instance"
    template:
      src: templates/{{ my_file }}/{{ item.name }}.{{ item.type }}.j2
      dest: /usr/lib/systemd/system/{{ item.name }}@.{{ item.type }}
      owner: root
      group: root
      mode: 0644
    with_items:
      "{{ systemd_units }}"

- import_playbook: retronas_system_config.yml
  vars:
    module_name: "adtpro"
    module_state: "present"