- hosts: localhost

  vars:
    - my_name: "ps3netsrv"
    - my_file: "install_ps3netsrv"

  tasks:

  - name: "{{ my_name }} - Load RetroNAS config"
    include_vars: retronas_vars.yml

  - name: "{{ my_name }} - Install build tools"
    apt:
       name: "{{ item }}"
       state: latest
    with_items:
      - make
      - automake
      - autoconf
      - gcc
      - g++
      - meson
      - ninja-build
      - curl
      - wget
      - build-essential
      - unzip
      - libmbedtls-dev
      - libmbedtls12
      - coreutils

  - name: "{{ my_name }} - build layout"
    file:
      src: "{{ item.src }}"
      dest: "{{ retronas_path }}/ps3/ps3netsrv/{{ item.dest }}"
      owner: "{{ retronas_user }}"
      group: "{{ retronas_user }}"
      state: link
    with_items:
      - { src: "../../roms/sony/playstation3/games", dest: "GAMES" }
      - { src: "../../roms/sony/playstation3/iso", dest: "PS3ISO" }
      - { src: "../../roms/sony/playstation2/dvd", dest: "PS2ISO" }
      - { src: "../../roms/sony/playstation1/iso", dest: "PSXISO" }
      - { src: "../../roms/sony/playstationportable/iso", dest: "PSPISO" }
      - { src: "../../roms/videos/bdiso", dest: "BDISO" }
      - { src: "../../roms/videos/dvdiso", dest: "DVDISO" }
    notify: "{{ my_name }} - Restart service"


  - name: "{{ my_name }} - Generate scripts"
    template:
      src: "templates/{{ my_file }}/{{ my_file }}.sh.j2"
      dest: "{{ retronas_root }}/scripts/{{ my_file }}.sh"
      owner: root
      group: root
      mode: 0755

  - name: "{{ my_name }} - Install from source code"
    shell: "{{ retronas_root }}/scripts/{{ my_file }}.sh 2>&1 | tee {{ retronas_root }}/log/{{ my_file }}.log"
    args:
      creates: "{{ retronas_root}} /bin/ps3netsrv"
    notify: "{{ my_name }} - Restart service"

  - name: "{{ my_name }} - create startup service"
    template:
      src: templates/{{ my_file }}/ps3netsrv.service.j2
      dest: /usr/lib/systemd/system/ps3netsrv.service
      owner: root
      group: root
      mode: 0644
    notify: "{{ my_name }} - Restart service"

  - name: "{{ my_name }} - enable startup service"
    service:
      name: "{{ item }}"
      state: started
      enabled: yes
      daemon_reload: yes
    with_items:
      - ps3netsrv

  handlers:

  - name: "{{ my_name }} - Restart service"
    service:
      name: "{{ item }}"
      state: restarted
      daemon_reload: yes
    with_items:
      - ps3netsrv

    
