- hosts: localhost

  vars:
    - my_name: "Generic ROM dir"
    - my_file: "install_romdir"

    - top_level_paths:
      - { name: "roms", enabled: "yes", systems: "yes" }

  tasks:
    - name: "{{ my_name }}"
      import_tasks: retronas_create_dirs.yml