- hosts: localhost

  vars:
    - my_name: "FSP for Swiss"
    - my_file: "install_fsp"

  tasks:

  - name: "{{ my_name }} - Load RetroNAS config"
    include_vars: retronas_vars.yml

  - name: "{{ my_name }} - Install build tools"
    apt:
       name: "{{ item }}"
       state: latest
    with_items:
      - python3
      - python-is-python3
      - build-essential
      - flex
      - gcc
      - scons

  - name: "{{ my_name }} - build top level dirs"
    file:
      path: "{{ retronas_path }}/gamecube/swiss/{{ item }}"
      owner: "{{ retronas_user }}"
      group: "{{ retronas_user }}"
      state: directory
      mode: "0775"
    with_items:
      - swiss
      - tmp
    notify: "{{ my_name }} - Restart service"
      
  - name: "{{ my_name }} - build layout"
    file:
      src: "{{ item.src }}"
      dest: "{{ retronas_path }}/gamecube/swiss/{{ item.dest }}"
      owner: "{{ retronas_user }}"
      group: "{{ retronas_user }}"
      state: link
    with_items:
      - { src: "../../roms/nintendo/gamecube/iso", dest: "games" }
    notify: "{{ my_name }} - Restart service"

  - name: "{{ my_name }} - Generate install scripts"
    template:
      src: "templates/{{ my_file }}/{{ my_file }}.sh.j2"
      dest: "{{ retronas_root }}/scripts/{{ my_file }}.sh"
      owner: root
      group: root
      mode: 0755

  - name: "{{ my_name }} - Install from source code"
    shell: "{{ retronas_root }}/scripts/{{ my_file }}.sh 2>&1 | tee {{ retronas_root }}/log/{{ my_file }}.log"
    #args:
      #creates: "{{ retronas_root}} /bin/fsp"
    notify: "{{ my_name }} - Restart service"

  - name: "{{ my_name }} - Generate config file"
    template:
      src: "templates/{{ my_file }}/fspd.conf.j2"
      dest: "{{ retronas_root }}/bin/fsp/etc/fspd.conf"
      owner: root
      group: root
      mode: 0755 

  - name: "{{ my_name }} - Set write permissions top level"
    copy:
      content: ""
      dest: "{{ retronas_path }}/gamecube/swiss/{{ item }}"
      force: no
      owner: "{{ retronas_user }}"
      group: "{{ retronas_user }}"
      mode: 0644
    with_items: 
      - .FSP_OK_ADD
      - .FSP_OK_DEL
      - .FSP_OK_MKDIR
      - .FSP_OK_RENAME

  - name: "{{ my_name }} - Set write permissions swiss subdir"
    copy:
      content: ""
      dest: "{{ retronas_path }}/gamecube/swiss/swiss/{{ item }}"
      force: no
      owner: "{{ retronas_user }}"
      group: "{{ retronas_user }}"
      mode: 0644
    with_items:
      - .FSP_OK_ADD
      - .FSP_OK_DEL
      - .FSP_OK_MKDIR
      - .FSP_OK_RENAME

  - name: "{{ my_name }} - create startup service"
    template:
      src: templates/{{ my_file }}/fspd.service.j2
      dest: /usr/lib/systemd/system/fspd.service
      owner: root
      group: root
      mode: 0644
    notify: "{{ my_name }} - Restart service"

  - name: "{{ my_name }} - enable startup service"
    service:
      name: "{{ item }}"
      state: started
      enabled: yes
      daemon_reload: yes
    with_items:
      - fspd

  handlers:

  - name: "{{ my_name }} - Restart service"
    service:
      name: "{{ item }}"
      state: restarted
      daemon_reload: yes
    with_items:
      - fspd

    
