- hosts: localhost

  vars:
    - my_name: "gogrepo"
    - my_file: "install_gogrepo"

  tasks:

  - name: "{{ my_name }} - Load RetroNAS config"
    include_vars: retronas_vars.yml

  - name: "{{ my_name }} - install dependencies"
    apt:
       name: "{{ item }}"
       state: latest
    with_items:
      - python3
      - python-is-python3
      - python3-html5lib
      - git
      - sudo

  - name: "{{ my_name }} - create GOG dir"
    file:
      path: "{{ retronas_path }}/{{ item }}"
      owner: "{{ retronas_user }}"
      group: "{{ retronas_user }}"
      mode: "0775"
      state: directory
    with_items:
      - gog

  - name: "{{ my_name }} - download gogrepo+patches (sairuk)"
    shell:
      chdir: "{{ retronas_root }}/bin"
      cmd: "git clone https://github.com/sairuk/gogrepo.git"
      creates: "{{ retronas_root }}/bin/gogrepo"

  - name: "{{ my_name }} - update gogrepo"
    shell: 
      chdir: "{{ retronas_root }}/bin/gogrepo"
      cmd: "git pull"

  - name: "{{ my_name }} - login script"
    template:
      src: "templates/{{ my_file }}/gogrepo_login.sh.j2"
      dest: "{{ retronas_root }}/scripts/gogrepo_login.sh"
      owner: root
      group: root
      mode: 0755

  - name: "{{ my_name }} - download script"
    template:   
      src: "templates/{{ my_file }}/gogrepo_download.sh.j2"
      dest: "{{ retronas_root }}/scripts/gogrepo_download.sh"
      owner: root
      group: root
      mode: 0755 

  - name: "{{ my_name }} - update script"
    template:
      src: "templates/{{ my_file }}/gogrepo_update.sh.j2"
      dest: "{{ retronas_root }}/scripts/gogrepo_update.sh"
      owner: root
      group: root
      mode: 0755
