- hosts: localhost

  vars:
    - my_name: "3DS QR Codes"
    - my_file: "install_3ds_qr_codes"

  tasks:

  - name: "{{ my_name }} - Load RetroNAS config"
    include_vars: retronas_vars.yml

  - name: "{{ my_name }} - configure CIA directory"
    file:
      path: "{{ retronas_path }}/3ds/cia"
      owner: "{{ retronas_user }}"
      group: "{{ retronas_group }}"
      state: directory

  - name: "{{ my_name }} - configure 3DS directory as symlink"
    file:
      src: "{{ retronas_path }}/roms/nintendo/3ds/cia"
      dest: "{{ retronas_path }}/3ds"
      state: link

  - name: "{{ my_name }} - configure QR codes directory"
    file:
      path: "{{ retronas_path }}/3ds/qr"
      owner: "{{ retronas_user }}"
      group: "{{ retronas_group }}"
      state: directory 

  - name: "{{ my_name }} - install qrencode"
    apt:
       name: qrencode
       state: latest

  - name: "{{ my_name }} - configure QR generator script"
    template:
      src: "templates/{{ my_file }}/3ds_qr.sh.j2"
      dest: "{{ retronas_root }}/scripts/3ds_qr.sh"
      owner: root
      group: root
      mode: '0755'
