- hosts: localhost

  vars:
    - my_name: "Generic ROM dir"
    - my_file: "install_romdir"
  tasks:

  - name: "{{ my_name }} - Load RetroNAS config"
    include_vars: retronas_vars.yml

  - name: "{{ my_name }} - build layout"
    file:
      path: "{{ retronas_path }}/roms/{{ item }}"
      owner: "{{ retronas_user }}"
      group: "{{ retronas_user }}"
      state: directory
      mode: "0775"
    with_items:
      - "acorn/archimedes"
      - "acorn/atom"
      - "acorn/bbcmicro"
      - "acorn/electon"
      - "amstrad/cpc"
      - "amstrad/pcw"
      - "apple/appleii"
      - "apple/macintosh"
      - "atari/2600"
      - "atari/5200"
      - "atari/7800"
      - "atari/800"
      - "atari/jaguar"
      - "atari/lynx"
      - "atari/st"
      - "bally/astrocade"
      - "bandai/rx78"
      - "bandai/wonderswan"
      - "cambridge_edsac"
      - "commodore/amiga"
      - "commodore/amigacd32"
      - "commodore/c16"
      - "commodore/c64"
      - "commodore/pet"
      - "commodore/vic20"
      - "fujitsu/fmtowns"
      - "fujitsu/fmtownsmarty"
      - "mame/hbmame"
      - "mame/mame"
      - "mattel/aquarius"
      - "mattel/intellivision"
      - "microsoft/msx"
      - "microsoft/xbox"
      - "microsoft/xbox360"
      - "nec/pc88"
      - "nec/pc98"
      - "nec/pcengine"
      - "nec/pcenginecd"
      - "nec/pcfx"
      - "nintendo/3ds"
      - "nintendo/ds"
      - "nintendo/famicom"
      - "nintendo/gameandwatch"  
      - "nintendo/gameboy"
      - "nintendo/gameboyadvance"
      - "nintendo/gameboycolor"
      - "nintendo/gamecube"
      - "nintendo/n64"
      - "nintendo/superfamicom"
      - "nintendo/virtualboy" 
      - "nintendo/wii"
      - "other/antonic_galaksija"
      - "other/coleco_colecovision"
      - "other/compukit_uk101"
      - "other/electronika_bk"
      - "other/emerson_arcadia2001"
      - "other/fairchild_channelf"
      - "other/generalinstrument_ay38500"
      - "other/interton_vc4000"
      - "other/jupiter_ace"
      - "other/magnavox_odyssey"
      - "other/magnavox_odyssey2"
      - "other/milesgordon_samcoupe"
      - "other/pelvarazdin_orao"
      - "other/radio_86rk"
      - "other/searle_multicomp"
      - "other/sord_m5"
      - "other/specialist_mx"
      - "other/spectravideo_sv328"
      - "other/tangerine_oric"
      - "other/tatung_einstein"
      - "other/tesla_ondraspo186"
      - "other/tesla_pmd85"
      - "other/texasinstruments_ti994a"
      - "other/vector06c"
      - "other/vectrex"
      - "sega/dreamcast"
      - "sega/mastersystem"
      - "sega/megacd"
      - "sega/megadrive"
      - "sega/saturn"
      - "sharp/mz"
      - "sharp/x68000"
      - "sinclair/ql"
      - "sinclair/zx81"
      - "sinclair/zxspectrum"
      - "snk/neogeo"
      - "snk/neogeopocket"
      - "sony/playstation1"
      - "sony/playstation2"
      - "sony/playstationportable"
      - "tandy/trs80"
      - "tandy/trs80colorcomputer1"
      - "tandy/trs80colorcomputer2"
      - "tandy/trs80colorcomputer3"
      - "tandy/trs80mc10"

  - name: "{{ my_name }} - build symlinks"
    file:
      src: "{{ item.src }}"
      dest: "{{ retronas_path }}/roms/{{ item.dest }}"
      owner: "{{ retronas_user }}"
      group: "{{ retronas_user }}"
      state: link
    loop:
      - { src: "nintendo/famicom", dest: "nintendo/nes" }
      - { src: "nintendo/superfamicom", dest: "nintendo/snes" }
      - { src: "sega/megadrive", dest: "sega/genesis" }
      - { src: "sega/megacd", dest: "sega/segacd" }
      - { src: "nec/pcengine", dest: "nec/turbografx16" }
      - { src: "nec/pcenginecd", dest: "nec/turbografxcd" }
