- hosts: localhost

  vars:
    - my_name: "ps3netsrv"
    - my_file: "install_ps3netsrv"

  tasks:

  - name: "{{ my_name }} - Load RetroNAS config"
    include_vars: retronas_vars.yml

  - name: "{{ my_name }} - Install build tools"
    apt:
       name: "{{ item }}"
       state: latest
    with_items:
      - make
      - automake
      - autoconf
      - gcc
      - g++
      - meson
      - ninja-build
      - curl
      - wget
      - build-essential
      - unzip
      - libmbedtls-dev
      - libmbedtls12 

  - name: "{{ my_name }} - create ps3/ps3netsrv directory"
    file:
      path: "{{ retronas_path }}/ps3/ps3netsrv/{{ item }}"
      owner: "{{ retronas_user }}"
      group: "{{ retronas_user }}"
      mode: "0775"
      state: directory
    with_items:
      - GAMES
      - PS3ISO
      - PS2ISO
      - PSXISO
      - PSPISO
      - BDISO
      - DVDISO

  - name: "{{ my_name }} - Install from source code"
    shell: "{{ retronas_root }}/scripts/{{ my_file }}.sh"
    args:
      creates: "{{ retronas_root}} /bin/ps3netsrv"
    notify: "{{ my_name }} - Restart service"

  - name: "{{ my_name }} - create startup service"
    template:
      src: templates/{{ my_file }}/ps3netsrv.service.j2
      dest: /usr/lib/systemd/system/ps3netsrv.service
      owner: root
      group: root
      mode: 0644
    notify: "{{ my_name }} - Restart service"

  - name: "{{ my_name }} - enable startup service"
    service:
      name: "{{ item }}"
      state: started
      enabled: yes
      daemon_reload: yes
    with_items:
      - ps3netsrv

  handlers:

  - name: "{{ my_name }} - Restart service"
    service:
      name: "{{ item }}"
      state: restarted
      daemon_reload: yes
    with_items:
      - ps3netsrv

    
