- hosts: localhost
  gather_facts: no

  vars:
    - my_name: "adtpro"
    - my_file: "install_{{ my_name }}"
    - my_dir: /opt/adtpro

    - systemd_units:
      - { name: "adtpro", type: 'service', state: "stopped", enabled: "no", restart: "no", instance: "no" }

    - packages:
      - default-jre
      - xvfb

    - templates:
      - { name: "{{ my_file }}.sh", dest: "{{ retronas_root }}/scripts", mode: "0755"}
      - { name: "ADTPro.properties", dest: "{{ my_dir }}", force: no}

  tasks:

  - name: "{{ my_name }} - Include systems map"
    include_vars: "retronas_systems.yml"

  - name: "{{ my_name }} - Load RetroNAS config"
    include_vars: retronas_vars.yml

  - name: "{{ my_name }} - Install build tools"
    package:
       name: "{{ packages }}"
       state: latest

  - name: "{{ my_name }} - path {{ my_dir }}"
    file:
      dest: "{{ my_dir }}"
      owner: "root"
      group: "root"
      mode: 0755

  - name: "{{ my_name }} - templates"
    template:
      src: "templates/{{ my_file }}/{{ item.name }}.j2"
      dest: "{{ item.dest }}/{{ item.name }}"
      owner: "{{ item.owner|default('root') }}"
      group: "{{ item.group|default('root') }}"
      mode: "{{ item.mode|default('0644') }}"
      force: "{{ item.force|default(yes) }}"
    with_items: "{{ templates }}"

  - name: "{{ my_name }} - Install"
    shell: "{{ retronas_root }}/scripts/{{ my_file }}.sh 2>&1 | tee {{ retronas_root }}/log/{{ my_file }}.log"
    args:
      creates: "{{ retronas_root}} {{ my_dir }}/adtpro.sh"

  - name: "{{ my_name }} - create startup service(s) instance"
    template:
      src: templates/{{ my_file }}/{{ item.name }}.{{ item.type }}.j2
      dest: /usr/lib/systemd/system/{{ item.name }}@.{{ item.type }}
      owner: root
      group: root
      mode: 0644
    with_items: "{{ systemd_units }}"
    notify: "{{ my_name }} daemon-reload only" 

  handlers:
    - name: "{{ my_name }} daemon-reload"
      systemd:
        daemon_reload: yes

- import_playbook: retronas_system_config.yml
  vars:
    module_name: "adtpro"
    module_state: "present"