system_map:
  - { src: "acorn/atom", mister: "AcornAtom" }
  - { src: "acorn/electron", mister: "AcornElectron" }
  - { src: "tandy/trs80mc10", mister: "AliceMC10" }
  - { src: "other/mits_altair8800", mister: "Altair8800" }
  - { src: "commodore/amiga", mister: "Amiga" }
  - { src: "amstrad/cpc", mister: "Amstrad" }
  - { src: "amstrad/pcw", mister: "Amstrad PCW" }
  - { src: "other/intel_x86", mister: "AO486" }
  - { src: "other/radio_86rk", mister: "APOGEE" }
  - { src: "apple/appleii", mister: "Apple-II" }
  - { src: "mattel/aquarius", mister: "AQUARIUS" }
  - { src: "other/emerson_arcadia2001", mister: "Arcadia" }
  - { src: "acorn/archimedes", mister: "ARCHIE" }
  - { src: "bally/astrocade", mister: "Astrocade" }
  - { src: "atari/2600", mister: "ATARI2600" }
  - { src: "atari/5200", mister: "ATARI5200" }
  - { src: "atari/7800", mister: "ATARI7800" }
  - { src: "atari/800", mister: "ATARI800" }
  - { src: "atari/lynx", mister: "AtariLynx" }
  - { src: "atari/st", mister: "AtariST" }
  - { src: "other/generalinstrument_ay38500", mister: "AY-3-8500" }
  - { src: "acorn/bbcmicro", mister: "BBCMicro" }
  - { src: "other/electronika_bk", mister: "BK0011M" }
  - { src: "commodore/commodore16", mister: "C16" }
  - { src: "commodore/commodore64", mister: "C64" }
  - { src: "other/fairchild_channelf", mister: "ChannelF" }
  - { src: "tandy/trs80colorcomputer2", mister: "CoCo2" }
  - { src: "tandy/trs80colorcomputer3", mister: "COCO3" }
  - { src: "other/coleco_colecovision", mister: "Coleco" }
  - { src: "other/cambridge_edsac", mister: "EDSAC" }
  - { src: "other/antonic_galaksija", mister: "Galaksija" }
  - { src: "nintendo/gameboy", mister: "GAMEBOY" }
  - { src: "nintendo/gameboy", mister: "GAMEBOY2P" }
  - { src: "nintendo/gameboyadvance", mister: "GBA" }
  - { src: "nintendo/gameboyadvance", mister: "GBA2P" }
  - { src: "sega/megadrive", mister: "Genesis" }
  - { src: "mame/hbmame", mister: "hbmame" }
  - { src: "mattel/intellivision", mister: "Intellivision" }
  - { src: "other/interact_homecomputer", mister: "Interact" }
  - { src: "other/jupiter_ace", mister: "Jupiter" }
  - { src: "other/videotechnology_vtechlaser", mister: "Laser" }
  - { src: "apple/macintosh", mister: "MACPLUS" }
  - { src: "mame/mame", mister: "mame" }
  - { src: "sega/megacd", mister: "MegaCD" }
  - { src: "microsoft/msx", mister: "MSX" }
  - { src: "other/searle_multicomp", mister: "MultiComp" }
  - { src: "snk/neogeo", mister: "NEOGEO" }
  - { src: "nintendo/famicom", mister: "NES" }
  - { src: "other/magnavox_odyssey2", mister: "ODYSSEY2" }
  - { src: "other/tesla_ondraspo186", mister: "Ondra_SPO186" }
  - { src: "other/pelvarazdin_orao", mister: "ORAO" }
  - { src: "other/tangerine_oric", mister: "Oric" }
  - { src: "nec/pc88", mister: "PC8801" }
  - { src: "commodore/pet", mister: "PET2001" }
  - { src: "other/tesla_pmd85", mister: "PMD85" }
  - { src: "sony/playstation1", mister: "PSX" }
  - { src: "sinclair/ql", mister: "QL" }
  - { src: "bandai/rx78", mister: "RX78" }
  - { src: "other/milesgordon_samcoupe", mister: "SAMCOUPE" }
  - { src: "sega/saturn", mister: "Saturn" }
  - { src: "sharp/mz", mister: "SharpMZ" }
  - { src: "sega/mastersystem", mister: "SMS" }
  - { src: "nintendo/superfamicom", mister: "SNES" }
  - { src: "other/sord_m5", mister: "Sord M5" }
  - { src: "sinclair/zxspectrum", mister: "Spectrum" }
  - { src: "other/specialist_mx", mister: "SPMX" }
  - { src: "other/spectravideo_sv328", mister: "SVI328" }
  - { src: "other/tatung_einstein", mister: "TatungEinstein" }
  - { src: "nec/pcengine", mister: "TGFX16" }
  - { src: "nec/pcenginecd", mister: "TGFX16-CD" }
  - { src: "other/texasinstruments_ti994a", mister: "TI-99_4A" }
  - { src: "tandy/trs80", mister: "TRS-80" }
  - { src: "other/zxevolution", mister: "TSConf" }
  - { src: "other/compukit_uk101", mister: "UK101" }
  - { src: "other/interton_vc4000", mister: "VC4000" }
  - { src: "other/vector06c", mister: "VECTOR06" }
  - { src: "other/vectrex", mister: "VECTREX" }
  - { src: "commodore/vic20", mister: "VIC20" }
  - { src: "bandai/wonderswan", mister: "WonderSwan" }
  - { src: "sharp/x68000", mister: "X68000" }
  - { src: "sinclair/zx81", mister: "ZX81" }
  - { src: "sinclair/zxspectrum", mister: "ZXNext" }
