- name: "{{ my_name }} - Include systems map"
  include_vars: "retronas_systems.yml"

- name: "{{ my_name }} - Load RetroNAS config"
  include_vars: retronas_vars.yml

- name: "{{ my_name }} - build layout list (set fact)"
  set_fact:
    path_list: "{{ path_list|default([]) }} + [ '{{ retronas_path }}/{{ item.1.name }}/{{ item.0.src if item.1.systems is true }}' ]"
  no_log: yes
  loop: "{{ system_map|product(top_level_paths)|list }}"
  when:
    - item.1.enabled is true

- name: "{{ my_name }} - build layout"
  shell:
    cmd: mkdir -p {{ path_list|flatten|join(' ') }}
  become: yes
  become_user: "{{ retronas_user }}"
  when: path_list is defined

- name: "{{ my_name }} - build x-system symlinks"
  file:
    src: "{{ retronas_path }}/{{ item.1.name }}/{{ item.0.src }}"
    dest: "{{ retronas_path }}/{{ item.1.name }}/{{ item.0.dest }}"
    owner: "{{ retronas_user }}"
    group: "{{ retronas_group }}"
    state: link
  with_nested:
    - "{{ system_links }}"
    - "{{ top_level_paths }}"
  when:
    - item.1.enabled is true
    - item.1.systems is true